version: '3.3'
services:

  frontend:
    container_name: frontend_react
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    container_name: server_ngnix
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/images/
    depends_on:
      - backend
      - frontend

  db:
    container_name: database
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend_api
    build:
      context: ../backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/images/ 
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
