# Generated by Django 2.2.16 on 2023-03-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230304_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsperrecipe',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='per_recipe', to='recipes.Ingredient'),
        ),
    ]
