# Generated by Django 3.2.18 on 2023-03-18 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230312_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user', 'recipe')},
        ),
        migrations.AlterModelOptions(
            name='ingredientsperrecipe',
            options={'ordering': ('recipe', 'ingredient')},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user', 'recipe')},
        ),
        migrations.AlterModelOptions(
            name='tagsonrecipe',
            options={'ordering': ('recipe', 'tag')},
        ),
        migrations.AlterField(
            model_name='ingredientsperrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Количество в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Время готовки'),
        ),
    ]
