# Generated by Django 3.2.18 on 2023-03-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230318_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsperrecipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
